### ISSUE TITLE
App Registration Issues

### ISSUE THREAD

**Issue by V1-SealeD** [microsoft/RdlMigration#23]
I cannot register an app using the App registration tool documented on https://dev.powerbi.com/apps It keeps returning the error "	An unknown network error occurred. Please try again." I have an account on an AD tenant, my account has a Power BI Pro licence and it has been assigned the Power BI Service Administrator permission on the tenant. 

Secondly, I create the app on Azure AD but no matter what I choose it is looking for a redirect url. Microsoft describes the redirect url as the URL your're accessing the app from but the app doesn't need to access any url or am I missing something? Finally in app registration > authentication >Advanced settings there is an option to treat the application as a public client for where a redirect URL is not used but this appears to have no impact on the authentication on the app when I run the rdl migration tool on the command prompt. I continue to receive either AADSTS50011 or AADSTS50013 errors.

**Comment by gboreki** [comment]
In the app registration for powerbi you need to select a "Native" application, which does not required a redirect url.

**Comment by V1-SealeD** [comment]
Thanks, it actually turned out to be a Microsoft issue that every user was experiencing when using https://dev.powerbi.com/apps. It has since been resolved.
