### ISSUE TITLE
Unable run this against the CM report server

### ISSUE THREAD

**Issue by FF03-CR** [microsoft/RdlMigration#24]
Hi, wanted to have some assistance maybe, if this work over the CM reports, if is known. I am trying to run this against test environment as we are integration PowerBI with our new CM release 2002, and I wanted to migrate our default reports to PowerBI. Following the instructions given I have an error right after logging. 

C:\Users\[user]\Desktop\Release>RdlMigration.exe http://servername/ReportServer "/ConfigMgr_000" "CAS_000" xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx
Starting the log-in window
One or more errors occurred.

log is not really helping much, "Starting the log-in window"

**Comment by gboreki** [comment]
Can you clarify what you mean by CM Report Server? You say this is from release 2002, we based the migration in the SOAP Apis introduced with SSRS 2008 R2, so they might not be compatible.

**Comment by FF03-CR** [comment]
CM Report Server is Configuration Manager Reporting Services which used to work over SSRS, our new build Configuration Manager 2002 (20 - 2002, 02 - February) integrate PowerBI, but the default reports will still RDLs, so I was to trying to migrate those to PowerBI. I am using SQL 2016

**Comment by gboreki** [comment]
This only works with SSRS/PBIRS configured to use windows authentication, configuration manager from what I recall installs a custom authentication extension which might be causing some issues. Would need to look at the logs from the server to confirm this.
