### ISSUE TITLE
Cloned Repo No RdlMigration.exe

### ISSUE THREAD

**Issue by itsnotaboutthecell** [microsoft/RdlMigration#28]
"The examples below assume that you are running in a command prompt where the application RdlMigration.exe was copied to."

Hello, I cloned the GitHub repo and was attempting to find the RdlMigration.exe file but have been unable to. Do I need to build this solution beforehand or are there some more guided steps that I can reference?

**Comment by gboreki** [comment]
Yes, you need to build the solution which will put RdlMigration.exe in the output folder. If you don't plan to build the project you can get the latest build from the artifacts:
https://github.com/microsoft/RdlMigration/releases/tag/CI_1791266
