### ISSUE TITLE
SSRS side permissions need?

### ISSUE THREAD

**Issue by krhacke33187** [microsoft/RdlMigration#29]
I am trying to run the package and am getting a permissions error from the SSRS side.  I have Browser, Content Manager, My Reports, Publisher, and Report Builder on the SSRS folders and content.  I have admin rights on the PBI workspace side.  What permissions are necessary on the SSRS side?
![Existing SSRS permissions](https://user-images.githubusercontent.com/57413655/91318358-bfec8380-e780-11ea-8ef9-1bb9390c9c4d.PNG)
![Script Error](https://user-images.githubusercontent.com/57413655/91318361-bfec8380-e780-11ea-83d7-37903d43be39.PNG)

**Comment by gboreki** [comment]
Hello,

You should have content manager permissions in all related items. Since the migration tool will look into the reports, but all its upstream dependencies such as shared datasets and shared data sources, you need permissions into all of those items as well.

Thanks
-G
