### ISSUE TITLE
Error when running the tool - "[folder] is neither a report nor a folder"

### ISSUE THREAD

**Issue by kasavin** [microsoft/RdlMigration#38]
I am getting the error "/Reports is neither a report nor a folder" when I run the application. 

I am able to log in successfully and retrieve reports from the server, but the Migration Tool can't seem to read a report in the top level folder: 

![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/2432736/130711706-114916aa-5929-4c11-a702-2e3369380189.png)

I've tried various permutations - please let me know what I need to do differently.

**Comment by gboreki** [comment]
Can you paste here what was the command line used?

**Comment by kasavin** [comment]
Thanks for your reply - I've moved on to other projects so can close this for now.
