### ISSUE TITLE
Report contains unsupported data source: of type: SHAREPOINTLIST.

### ISSUE THREAD

**Issue by dixi1984** [microsoft/RdlMigration#41]
Is it possible to migrate Reports with Sharepoint List as DataSource. I'm getting this error;

Report contains unsupported data source: <pii>Source</pii>, of type: SHAREPOINTLIST.

**Comment by gboreki** [comment]
Unfortunately sharepoint list datasources are not yet supported in the powerbi service, so the automatic conversion is rejected by the service during upload.

The workaround for this scenario is to create a PBIDataset that uses the Sharepoint List directly in the service, and then point your RDL Report to that dataset. This tool does not automate that process, so you would need to create the datasets manually.
