### ISSUE TITLE
Power BI Server support

### ISSUE THREAD

**Issue by ryno1234** [microsoft/RdlMigration#42]
I find it strange that much of the Microsoft documentation as well as the documentation here doesn't explicitly reference the fact that this is for Power BI Service and not compatible with Power BI Server. 

Am I missing something? From looking at the code, there are constants defined which reference the Power BI Service API at a specific URL with no capability, from what I can tell, to reference a local Power BI Server.

More strange to me is that even searches for this issue turn up results that only discuss Power BI Service's API. Is there a reason why the Power BI Server is not referenced when it comes to this subject? Maybe I'm missing something.

All that said, I have a need to migrate RDL's to Power BI Server. Do you have any suggestions of how to accomplish this without having to roll my own transfer util?

**Comment by gboreki** [comment]
Power BI Report Server is a super set of SSRS, so you are able to just import the entire catalog into a reportserver, or use the powershell scripts to download and reupload in the server. What this tool does is to replace features that are not supported in the powerbi service with equivalent features. You can check more about the powershell scripts here: https://github.com/Microsoft/ReportingServicesTools
